version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: celery -A server worker --beat
    depends_on:
      - web


  web:
    build:
      context: ./
      dockerfile: Dockerfile

    depends_on:
      - db


  db:
    image: postgres:16.0-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lic/postgresql/data/
    expose:
      - "5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

  
volumes:
  postgres_data:
  static_volume: