# Generated by Django 4.2 on 2024-09-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rss_id', models.CharField(max_length=200, unique=True)),
                ('published', models.DateTimeField()),
                ('summary', models.TextField()),
                ('is_analysed', models.BooleanField(default=False)),
                ('is_positive', models.CharField(choices=[('P', 'POSITIVE'), ('N', 'NEGATIVE'), ('A', 'NEUTRAL')], default='A')),
                ('tickers', models.ManyToManyField(to='tickers.ticker')),
            ],
        ),
    ]
