# Generated by Django 4.2 on 2024-03-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='is_analysed',
            field=models.BooleanField(default=False),
        ),
    ]
