# Generated by Django 4.2 on 2024-09-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
        ('rss_component', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='tickers',
            field=models.ManyToManyField(related_name='rss', to='tickers.ticker'),
        ),
    ]
