# Generated by Django 4.2 on 2024-08-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_component', '0003_rssfeed_is_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='is_positive',
            field=models.CharField(choices=[('P', 'POSITIVE'), ('N', 'NEGATIVE'), ('A', 'NEUTRAL')], default='A'),
        ),
    ]
