# Generated by Django 4.2 on 2024-09-18 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('withdraw_value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('historic_value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
