# Generated by Django 4.2 on 2024-10-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starting_value',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='withdraw_value',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_investment',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='historic_investment',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True),
        ),
    ]
