version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: celery -A server worker --beat


  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/home/app/static
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lic/postgresql/data/
    expose:
      - "5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

  
volumes:
  postgres_data:
  static_volume: