version: '3'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:13.0-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lic/postgresql/data/
    expose:
      - "5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"

  
volumes:
  postgres_data: