# Generated by Django 4.2 on 2024-09-03 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('date_investment', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('annual_returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=150, default=0, max_digits=200)),
                ('starting_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('withdraw_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_return', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_volatility', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_variance', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='port', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_created=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_buy', models.DateTimeField(blank=True, null=True)),
                ('is_sell', models.BooleanField(default=False)),
                ('starting_investment', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('current_value', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('close_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('starting_value_of_ticker', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('current_value_of_ticker', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_tickers', to='portfolio.portfolio')),
                ('ticker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker')),
            ],
        ),
    ]
