# Generated by Django 5.2.4 on 2025-08-03 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('tickers', '0003_ticker_price_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticker',
            name='ticker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='tickers.ticker'),
            preserve_default=False,
        ),
    ]
