# Generated by Django 5.2.4 on 2025-08-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('simply_return', models.DecimalField(decimal_places=3, default=0, help_text='Simply Rate of Return', max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='TickerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, unique=True)),
                ('key_words', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('label', models.CharField(max_length=240)),
            ],
            options={
                'unique_together': {('title', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('ticker', models.CharField(max_length=200, null=True, unique=True)),
                ('indices', models.CharField(choices=[('^GSPC', 'SP500'), ('^IXIC', 'NASDAQ'), ('^GDAXI', 'GERMAN_DAX'), ('^FTSE', 'LONDON_FTSE')], default='^GSPC', max_length=10)),
                ('beta', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('market_variance', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('camp', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=8, default=0, help_text='Price change last day', max_digits=30, null=True)),
                ('price_avg', models.DecimalField(decimal_places=3, default=0, max_digits=30)),
                ('simply_return', models.DecimalField(decimal_places=3, default=0, help_text='Simply Rate of Return', max_digits=30)),
                ('log_return', models.DecimalField(decimal_places=8, default=0, help_text='Log Return', max_digits=30)),
                ('standard_deviation', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('sharp', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('wikipedia_url', models.URLField(blank=True, null=True)),
                ('prediction', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('date_predict', models.DateField(blank=True, null=True)),
                ('ticker_tags', models.ManyToManyField(to='tickers.tags')),
                ('ticker_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickers.tickercategory')),
            ],
        ),
        migrations.CreateModel(
            name='TickerDataFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=220)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pct_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_df', to='tickers.ticker')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
