# Generated by Django 4.2 on 2024-09-12 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('simply_return', models.DecimalField(decimal_places=3, default=0, help_text='Simply Rate of Return', max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('date_investment', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('annual_returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=150, default=0, max_digits=200)),
                ('starting_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('withdraw_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_return', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_volatility', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_variance', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('label', models.CharField(max_length=240)),
            ],
            options={
                'unique_together': {('title', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('ticker', models.CharField(max_length=200, null=True)),
                ('indices', models.CharField(choices=[('^GSPC', 'SP500'), ('^IXIC', 'NASDAQ'), ('^GDAXI', 'GERMAN_DAX'), ('^FTSE', 'LONDON_FTSE')], default='^GSPC', max_length=10)),
                ('beta', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('market_variance', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('camp', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('price_avg', models.DecimalField(decimal_places=3, default=0, max_digits=30)),
                ('simply_return', models.DecimalField(decimal_places=3, default=0, help_text='Simply Rate of Return', max_digits=30)),
                ('log_return', models.DecimalField(decimal_places=8, default=0, help_text='Log Return', max_digits=30)),
                ('standard_deviation', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('sharp', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('wikipedia_url', models.URLField(blank=True, null=True)),
                ('prediction', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('date_predict', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TickerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, unique=True)),
                ('key_words', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('date_buy', models.DateTimeField(blank=True, null=True)),
                ('is_sell', models.BooleanField(default=False)),
                ('starting_investment', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('current_value', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('close_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('starting_value_of_ticker', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('current_value_of_ticker', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_tickers', to='tickers.portfolio')),
                ('ticker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker')),
            ],
        ),
        migrations.AddField(
            model_name='ticker',
            name='ticker_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickers.tickercategory'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ticker_tags',
            field=models.ManyToManyField(to='tickers.tags'),
        ),
        migrations.CreateModel(
            name='TickerDataFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=220)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pct_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_df', to='tickers.ticker')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
