# Generated by Django 4.2 on 2024-01-04 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('date_investment', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('annual_returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=150, default=0, max_digits=200)),
                ('starting_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('maximum_cash', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_return', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_volatility', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('expected_portfolio_variance', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('ticker', models.CharField(max_length=200, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('market_variance', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('camp', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('simply_return', models.DecimalField(decimal_places=8, default=0, help_text='Simply Rate of Return', max_digits=30)),
                ('log_return', models.DecimalField(decimal_places=8, default=0, help_text='Log Return', max_digits=30)),
                ('standard_deviation', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('sharp', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickers.group')),
            ],
        ),
        migrations.CreateModel(
            name='UserTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('date_buy', models.DateTimeField(blank=True, null=True)),
                ('is_buy', models.BooleanField(default=False)),
                ('is_sell', models.BooleanField(default=False)),
                ('starting_investment', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('current_value', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('starting_value_of_ticker', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('current_value_of_ticker', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='tickers.portfolio')),
                ('ticker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker')),
            ],
        ),
    ]
