# Generated by Django 4.2 on 2024-01-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='simply_return',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Simply Rate of Return', max_digits=30),
        ),
    ]
