# Generated by Django 4.2 on 2024-09-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userticker',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='userticker',
            name='ticker',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='UserTicker',
        ),
    ]
