# Generated by Django 5.2.4 on 2025-08-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0002_alter_ticker_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='price_change',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, help_text='Price change last day', max_digits=30, null=True),
        ),
    ]
