# Generated by Django 4.2 on 2024-01-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0003_tickerdataframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdataframe',
            name='date',
            field=models.CharField(default='', max_length=220),
        ),
    ]
