# Generated by Django 5.2.4 on 2025-08-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0003_ticker_price_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='kurtosis',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='3> chances for big movements either plus ', max_digits=10),
        ),
        migrations.AddField(
            model_name='ticker',
            name='skewness',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Negative value chance for big damages, positive chance for unexpected winnings', max_digits=10),
        ),
    ]
