# Generated by Django 5.2.4 on 2025-08-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0004_ticker_kurtosis_ticker_skewness'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='correlation',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Against the market', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sharp',
            field=models.DecimalField(decimal_places=8, default=0, help_text='The Sharpe ratio is a measure of the risk-adjusted return of an investment Ahigher Sharpe ratio indicates that an investment provides higher returns fora given level of risk compared to other investments with a lower Sharpe ratioIn general, a Sharpe ratio under 1.0 is considered bad, equal to 1.0 is considered acceptable or good, 2.0 or higher is rated as very good, and 3.0 or higher is considered excellent.', max_digits=30),
        ),
    ]
