# Generated by Django 4.2 on 2024-01-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0005_remove_tickerdataframe_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('simply_return', models.DecimalField(decimal_places=3, default=0, help_text='Simply Rate of Return', max_digits=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='group',
        ),
        migrations.AddField(
            model_name='ticker',
            name='indices',
            field=models.CharField(choices=[('^GSPC', 'SP500'), ('^IXIC', 'NASDAQ'), ('^GDAXI', 'GERMAN_DAX'), ('^FTSE', 'LONDON_FTSE')], default='^GSPC', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
