# Generated by Django 4.2 on 2024-01-14 17:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0006_indices_remove_ticker_group_ticker_indices_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
