# Generated by Django 4.2 on 2024-02-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0008_ticker_price_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='is_locked',
        ),
    ]
