# Generated by Django 4.2 on 2024-03-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0009_remove_portfolio_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='indices',
            field=models.CharField(choices=[('^GSPC', 'SP500'), ('^IXIC', 'NASDAQ'), ('^GDAXI', 'GERMAN_DAX'), ('^FTSE', 'LONDON_FTSE')], default='^GSPC', max_length=10),
        ),
        migrations.AlterField(
            model_name='userticker',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_tickers', to='tickers.portfolio'),
        ),
    ]
