# Generated by Django 4.2 on 2024-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0010_alter_ticker_indices_alter_userticker_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerdataframe',
            name='pct_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
