# Generated by Django 4.2 on 2024-05-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0011_tickerdataframe_pct_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickerdataframe',
            options={'ordering': ['-date']},
        ),
    ]
