# Generated by Django 4.2 on 2024-06-16 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0012_alter_tickerdataframe_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, unique=True)),
                ('key_words', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticker',
            name='ticker_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickers.tickercategory'),
        ),
    ]
