# Generated by Django 4.2 on 2024-07-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0015_alter_tickerdataframe_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userticker',
            name='is_buy',
        ),
        migrations.AddField(
            model_name='userticker',
            name='close_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
