# Generated by Django 4.2 on 2024-07-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0016_remove_userticker_is_buy_userticker_close_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='maximum_cash',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='withdraw_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
