# Generated by Django 4.2 on 2024-08-02 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0017_remove_portfolio_maximum_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerAvalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker', unique=True)),
            ],
        ),
    ]
