# Generated by Django 4.2 on 2024-08-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0018_ticker_wikipedia_url_tags'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TickerAvalysis',
            new_name='TickerAnalysis',
        ),
    ]
